#!/bin/bash
set -eu

# Go to project home
PROJ=$(pipenv --where 2>/dev/null)
cd ${PROJ:?Could not find project home}

# Skip configuration if not installed
if ! pip list | grep ipython >/dev/null 2>&1
then
    exit 0
fi

# Write environment variables to .env
IPYTHONDIR=${PROJ}/.ipython
echo IPYTHONDIR=${IPYTHONDIR} >> .env

# Create IPython profile
mkdir -p ${IPYTHONDIR}
pipenv run ipython profile create default --ipython-dir ${IPYTHONDIR}
