#!/bin/bash
set -eu

# Go to project home
PROJ=$(pipenv --where 2>/dev/null)
cd ${PROJ:?Could not find project home}

# Skip configuration if not installed
if ! cat ${PROJ}/Pipfile | grep jupyter >/dev/null 2>&1
then
    exit 0
fi

# Write environment variables to .env
JUPYTER_CONFIG_DIR=${PROJ}/.jupyter
echo JUPYTER_CONFIG_DIR=${JUPYTER_CONFIG_DIR} >> .env

# Create Jupyter kernel
mkdir -p ${JUPYTER_CONFIG_DIR}
pipenv run ipython kernel install --sys-prefix --profile default --display-name Default
