#!/bin/bash
set -eu

# Go to project home
PROJ=$(pipenv --where 2>/dev/null)
cd ${PROJ:?Could not find project home}

# Skip configuration if not installed
if ! pip list | grep matplotlib >/dev/null 2>&1
then
    exit 0
fi

# Write environment variables to .env
MATPLOTLIBRC=${PROJ}/.matplotlib
MPLCONFIGDIR=${PROJ}/.matplotlib
echo MATPLOTLIBRC=${MATPLOTLIBRC} >> .env
echo MPLCONFIGDIR=${MPLCONFIGDIR} >> .env

# Create empty matplotlibrc and stylelib directory
mkdir -p ${MATPLOTLIBRC}
mkdir -p ${MPLCONFIGDIR}/stylelib
touch ${MATPLOTLIBRC}/matplotlibrc
