#!/bin/bash
set -eu
shopt -s nullglob

# Go to project home
PROJ=$(pipenv --where 2>/dev/null)
cd ${PROJ:?Could not find project home}

# run hook if exists
for HOOK in ${PROJ}/hooks/hook-pre*
do
    pipenv run ${HOOK}
done
